spring:
  application:
    name: campus-transparency

  datasource:
    url: jdbc:postgresql://localhost:5432/campus_transparency
    username: campus_app
    password: "@Om1kadam1"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ⬅ AUTO SCHEMA ENABLED
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

server:
  port: 8080
